parameters:
#    tkgl_core.example.class: Tkgl\CoreBundle\Example

services:
#    tkgl_core.example:
#        class: %tkgl_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
